# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:
- task: gitsync@1
  inputs:
    GitRepoUrl: 'https://github.com/ahmedgalal007/AkhbarElyomFrontEnd2021.git'



- task: CmdLine@2
  inputs:
    script: |
      dotnet tool install -g  microsoft.web.librarymanager.cli --version 2.1.113
      dotnet tool update --global dotnet-ef --version 5.0.0

- task: NuGetToolInstaller@1

- task: NodeTool@0
  inputs:
    versionSpec: '12.18.3'

- script: npm install -g gulp-cli

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: cd akhbarelyom.front.end.2021\MVC && npm install 


- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
